title: EvoniX Roleplay Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.evonix-rp.com/'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 — Jan 2'
  down: '#e60000'
  systems:
    - name: Roleplay Server
      category: EvoniX Server
      partial: ''
    - name: Development Server
      category: EvoniX Server
    - name: Main Site
      category: Websites
    - name: Forums
      category: Websites
    - name: LSPD Forums
      category: Websites
    - name: LSFD Forums
      category: Websites
    - category: UCP
      name: UCP Site
    - name: API
      category: UCP
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#0a0c0f'
  headerTextColor: white
  logo: /img/evonix-logo.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Support Center
      link: 'https://support.evonix-rp.com'
  alwaysKeepBrandColor: false
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: none
  ok: '#008000'
  categories:
    - name: EvoniX Server
      closed: false
      description: EvoniX Roleplay server current status right over here.
      untited: false
    - name: UCP
      description: EvoniX Roleplay UCP API & Site Information
    - name: Websites
      description: >-
        EvoniX Roleplay websites such as Landing Page, EvoniX Forum, LSPD Forum
        & LSFD Forum.
      closed: false
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
