title: Status - EvoniX Roleplay
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.evonix-rp.com/
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Game Server - Roleplay Server
      category: Server
      partial: ""
      description: EvoniX Roleplay game server status.
    - category: Server
      name: User Control Panel
      description: UCP website status.
    - name: Forums
      category: Server
      description: Evonix Roleplay forums status.
    - name: Los Santos Police Department Forums
      category: Server
      description: Right here about Police Department forums status.
    - name: Los Santos Fire Department Forums
      category: Server
      description: Right here about Fire Department forums status.
    - name: Legal Faction Teamspeak
      category: Server
      description: Legal Faction Teamspeak status.
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/evonix-logo.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: false
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: none
  ok: "#008000"
  categories:
    - name: Server
      closed: false
      description: Related to all EvoniX Roleplay server including forums and ucp.
      untited: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
